# View Assist - Spell a Word (v 1.0.0)
# Written by - Dinki
blueprint:
  name: View Assist - Spell a Word
  description: Ask Assist to spell a word and it spells the word letter-by-letter and displays the word on screen where applicable (View Assist spellaword v 1.0.0)
  domain: automation
  input:
    command_prompt:
      name: Command Text
      description: The phrase you want to use to trigger the automation
      default: "[please] [how do you| can you] spell {word}"                 
    view:
      name: Dashboard view
      description: The View Assist dashboard view to use for displaying text (example /dashboard-viewassist/info)
      default: "/view-assist/info" 
alias: View Assist - Spell a Word
description: "Ask Assist to spell a word and it spells the word letter-by-letter and displays the word on screen where applicable"
trigger:
  - platform: conversation
    command:
      - !input command_prompt
condition: []
action:
  - action: view_assist.get_target_satellite
    data:
      device_id: "{{ trigger.device_id }}"
    response_variable: target_satellite
  - variables:
      target_satellite_device: "{{ target_satellite.target_satellite[0] }}"
      target_musicplayer_device: "{{ state_attr(target_satellite_device, 'musicplayer_device')}}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
      command_prompt: !input command_prompt
      view: !input view      
  - set_conversation_response: >-
      {{ trigger.slots.word }} is spelled  ... {% set spaced_text = '...
      '.join(trigger.slots.word) %}{{ spaced_text }}
  - if:
      - condition: template
        value_template: >-
          {% if target_satellite_device_type != 'audio_only' %}true{% else
          %}false{% endif %}
    then:
      - action: view_assist.set_state
        target:
          entity_id: "{{ target_satellite_device }}"
        data:
          title: ""
          message: <center>{{ trigger.slots.word |upper }}</center>
          message_font_size: 6vw
      - action: view_assist.navigate
        data:
          device: "{{ target_satellite_device }}"
          path: "{{ view }}"
mode: single