# View Assist - Tell Me a Joke(v 1.0.0)
blueprint:
  name: View Assist - Tell Me a Joke
  description: Ask Assist to tell you a joke and get ready to laugh or groan (View Assist tellmeajoke v 1.0.0)
  domain: automation
  input:
    command:
      name: Command 
      description: The phrase you want to use to trigger the joke request
      default: "tell [me | us] a joke"
alias: View Assist - Tell me a joke
description: ""
trigger:
  - platform: conversation
    command:
      - !input command
condition: []
action:
  - action: view_assist.get_target_satellite
    data:
      device_id: "{{ trigger.device_id }}"
    response_variable: target_satellite
  - variables:
      target_satellite_device: "{{ target_satellite.target_satellite[0] }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
  - service: pyscript.viewassist_get_dadjoke
    data: {}
    response_variable: joke_response
  - set_conversation_response: "{{ joke_response['joke']  }}"
    enabled: true
mode: single