blueprint:
  name: View Assist - How's the Weather?
  description: Ask "How's the Weather?" and ViewAssist will respond with the weather
    and show the weather view (View Assist howstheweather v 1.0.0)
  domain: automation
  input:
    command_prompt:
      name: Command Text
      description: The phrase you want to use to trigger the automation
      default: (How's | How is | What's | What is) [the] weather
    weather_entity:
      name: Weather Entity
      description: The entity that provides weather information (example weather.home)
      selector:
        entity:
          filter:
          - domain:
            - weather
          multiple: false
    dashboard:
      name: Dashboard Weather view
      description: The View Assist dashboard view to use for weather (example /dashboard-viewassist/weather)
      default: /view-assist/weather
  source_url: https://raw.githubusercontent.com/dinki/View-Assist/main/View_Assist_custom_sentences/Hows_the_weather/blueprint-howstheweather.yaml
alias: View Assist - How's the weather
description: Provides information on the current weather and forecast
trigger:
- platform: conversation
  command: !input command_prompt
variables:
  weather_entity: !input weather_entity
  dashboard: !input dashboard
condition: []
action:
- data:
    device_id: "{{ trigger.device_id }}"
  response_variable: target_satellite
  action: view_assist.get_target_satellite
- variables:
    target_satellite_device: "{{ target_satellite.target_satellite[0] }}"
    target_mediaplayer_device: '{{ state_attr(target_satellite_device, ''mediaplayer_device'')}}'
    target_satellite_device_type: '{{ state_attr(target_satellite_device, ''type'')}}'
    target_display_type: '{{ state_attr(target_satellite_device, ''display_type'')}}'      
  enabled: true
- set_conversation_response: Its {{ state_attr(weather_entity, 'temperature') }} degrees
    and {{states[weather_entity].state}}
  enabled: true
- if:
  - condition: template
    value_template: '{% if target_satellite_device_type != ''audio_only'' %}true{%
      else %}false{% endif %}'
  then:
  - data:
      device: "{{ target_satellite_device }}"
      display_type: "{{ target_display_type }}"
      path: "{{ dashboard }}"
    action: view_assist.navigate
  enabled: true
mode: single
