navigate:
  name: Navigate to a view
  description: >
    Command device to navigate to a certain view
  fields:
    device:
      name: Device
      description: The device to change screen on
      example: "123434"
      required: true
      selector:
        entity:
          filter:
            integration: view_assist
    path:
      name: View Path
      description: Path in dashboard view
      example: "/view-assist/clock"
      required: true
      selector:
        text:
    revert:
      name: Revert Display
      description: Revert to home screen after display timeout - default is yes
      required: false
      selector:
        boolean:
    timeout:
      name: Timeout
      description: Timeout to revert the screen in seconds
      required: false
      selector:
        number:
set_state:
  name: Set state or attributes
  description: >
    Set state or attributes of View Assist entity
  target:
    entity:
      integration: view_assist
      domain:
        - sensor
  fields:
    state:
      name: "State"
      description: "Entity state"
      selector:
        text:
set_timer:
  name: Set a timer
  description: Set an alarm, timer or reminder
  fields:
    device_id:
      name: "Device ID"
      description: "Device id of the voice satellite"
      required: true
      selector:
        text:
    type:
      name: "Timer type"
      description: "The type of timer - alarm, timer or reminder"
      required: true
      selector:
        select:
          options:
            - "Alarm"
            - "Timer"
            - "Reminder"
    name:
      name: "Name"
      description: "The name of the timer"
      required: false
      selector:
        text:
    time:
      name: "Time sentence"
      description: "A spoken like time sentence"
      required: true
      selector:
        text:
cancel_timer:
  name: "Cancel timer"
  description: "Cancel running timer"
  fields:
    timer_id:
      name: "Timer ID"
      description: "The id of the timer"
      required: false
      selector:
        text:
    device_id:
      name: "Device ID"
      description: "The id of the voice satellite device to cancel all timers for"
      required: false
      selector:
        text:
    remove_all:
      name: "Remove all"
      description: "Cancel all timers"
      required: false
      selector:
        boolean:
get_timers:
  name: "Get timers"
  description: "Get all timers or by timer id or device id"
  fields:
    timer_id:
      name: "Timer ID"
      description: "The id of the timer"
      required: false
      selector:
        text:
    device_id:
      name: "Device ID"
      description: "The id of the voice satellite device to get all timers for"
      required: false
      selector:
        text:


