navigate:
  name: Navigate to a view
  description: >
    Command device to navigate to a certain view
  fields:
    device:
      name: Device
      description: The device to change screen on
      example: "123434"
      required: true
      selector:
        entity:
          filter:
            integration: view_assist
    path:
      name: View Path
      description: Path in dashboard view
      example: "view_assist/clock"
      required: true
      selector:
        text:
set_state:
  name: Set state or attributes
  description: >
    Set state or attributes of View Assist entity
  target:
    entity:
      integration: view_assist
      domain:
        - sensor
  fields:
    state:
      name: "State"
      description: "Entity state"
      selector:
        text:
